android: fix BottomSheetScaffold animation crash in tap mode
- Change partialExpand() to hide() when closing the menu sheet in tap mode;
  partialExpand() is not supported by BottomSheetScaffold and causes
  IllegalStateException: 'Attempted to animate to hidden when
  skipHiddenState was enabled'
- This was causing the app to crash when tapping the menu handle,
  resulting in perceived slow startup and timeouts